### ISSUE TITLE
openjpa-enhancer exception with Java 8

### ISSUE THREAD

**Issue by nicolas-rempulski** [wisdom-framework/wisdom-jdbc#21]
I migrated my project to Wisdom 0.10.0-SNAPSHOT and tried to set my Java compilation source and target to Java 8.

An exception occur while the project is building : 

[ERROR] Failed to execute goal org.wisdom-framework:wisdom-openjpa-enhancer-plugin:0.6-SNAPSHOT:enhance-entities (enhancer) on project yggdrasil: Execution enhancer of goal org.wisdom-framework:wisdom-openjpa-enhancer-plugin:0.6-SNAPSHOT:enhance-entities failed. IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wisdom-framework:wisdom-openjpa-enhancer-plugin:0.6-SNAPSHOT:enhance-entities (enhancer) on project yggdrasil: Execution enhancer of goal org.wisdom-framework:wisdom-openjpa-enhancer-plugin:0.6-SNAPSHOT:enhance-entities failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:364)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution enhancer of goal org.wisdom-framework:wisdom-openjpa-enhancer-plugin:0.6-SNAPSHOT:enhance-entities failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 24 more
Caused by: java.lang.IllegalArgumentException
	at org.apache.xbean.asm4.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm4.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm4.ClassReader.<init>(Unknown Source)
	at org.apache.openjpa.enhance.AsmAdaptor.toJava7ByteArray(AsmAdaptor.java:93)
	at org.apache.openjpa.enhance.AsmAdaptor.writeJava7(AsmAdaptor.java:84)
	at org.apache.openjpa.enhance.AsmAdaptor.write(AsmAdaptor.java:54)
	at org.apache.openjpa.enhance.PCEnhancer.record(PCEnhancer.java:633)
	at org.apache.openjpa.enhance.PCEnhancer.record(PCEnhancer.java:619)
	at org.apache.openjpa.enhance.PCEnhancer.run(PCEnhancer.java:4900)
	at org.apache.openjpa.enhance.PCEnhancer.run(PCEnhancer.java:4830)
	at org.apache.openjpa.enhance.PCEnhancer$1.run(PCEnhancer.java:4800)
	at org.apache.openjpa.lib.conf.Configurations.launchRunnable(Configurations.java:764)
	at org.apache.openjpa.lib.conf.Configurations.runAgainstAllAnchors(Configurations.java:754)
	at org.apache.openjpa.enhance.PCEnhancer.run(PCEnhancer.java:4795)
	at org.wisdom.openjpa.enhancer.OpenJPAEnhancerMojo.enhance(OpenJPAEnhancerMojo.java:424)
	at org.wisdom.openjpa.enhancer.OpenJPAEnhancerMojo.execute(OpenJPAEnhancerMojo.java:213)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 25 more

This issue seems linked with ASM version : http://stackoverflow.com/questions/25611851/java-lang-illegalargumentexception-at-org-apache-xbean-asm4-classreader-init

**Comment by cescoffier** [comment]
Can you try the version from master ?

**Comment by nicolas-rempulski** [comment]
Compiled & tested, it works fine for me.

Thanks !

2015-10-19 8:32 GMT+02:00 Clement Escoffier <notifications@github.com>:
